name: build with UI tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Prepare xvfb and build with Maven
        run: |
          Xvfb :99 &>/dev/null &
          export DISPLAY=:99.0
          mvn -Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Denable.ui.tests=true -Dheadless.geometry=1920x1080-32 --batch-mode --update-snapshots package
